# Generated by Django 5.1.2 on 2024-10-30 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocated_time', models.PositiveIntegerField(help_text='Allocated time in seconds')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('timer_start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
